### PR TITLE
Bug/add inr

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

Adds support for currency INR. Similar to https://github.com/eventespresso/event-espresso-core/pull/593

## How has this been tested

* [ ] you should just be able to set your country to India, and then paypal smart buttons shouldn't give any warning

## Checklist

* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by Pebblo** [comment]
Codewise this gets a thumbs up from me, but.... I wasn't sure what API Smart Buttons and as the docs I was looking at for #593 specially mentioned 'Express Checkout, PayPal Payments Standard, and Website Payments Pro APIs' I did some digging and found this (which I'm guessing you checked anyway):
https://developer.paypal.com/docs/integration/direct/rest/currency-codes/

Just in case this specific integration didn't support this currency for some random reason.

Anyway, just added the above for reference.

**Comment by mnelson4** [comment]
ah, no I didn't look over that list. Ya, I suppose their REST API supports different currencies, among which INR isn't one. So this doesn't need to be done on this integration. Thanks @Pebblo !

**Comment by Pebblo** [comment]
INR is listed in the currencies there, unless I'm missing something else shouldn't that mean it supports?

**Comment by mnelson4** [comment]
oh dang, I searched through the page but must have searched for "RNI" or something. ugh. Ok so it is in that list, so this should be merged.

**Comment by Pebblo** [comment]
So I was going to try and test this, but turns out India payments are a pain to test with PayPal, I tried doing so in [#593](https://github.com/eventespresso/event-espresso-core/pull/593) and in the end, we just merged the text change to allow for INR support.

So I'm merging this in.

**Pull request merged**
