### PR TITLE
Pull the payment from PayPal and use the data from that

### PR DESCRIPTION
**Pull request by Pebblo**
Hey @mnelson4,

I hope you don't mind as this is a bit out of the blue, when we started getting reports of the payer_id error I started doing a little digging into it and notice a few different examples used this method to get the details so I gave it a go and so far... payments work as expected and if I'm right in how I think this works, should 'wait' until we have the details needed before it submits.

So first, please feel free to drop this PR if you don't want to use it, I'm certainly no JS master this is just what I ended up with from when I started looking at it as a side project.

Just to run through how I think this now works:

In this branch, rather than just using the paymentToken data (named authData in this version) and hopefully setting the details before triggering the button click, this branch uses those details and sets everything you did previously but then pulls the payment from PayPal again and uses the values we need from that.

`actions.payment.get()` pulls the payment, but this time you get a payment object so don't have all of the same details, however, you do get the payment_id and payer_id which appear to be the only values that are actually used anyway?

So in short, this uses all the values it used to, but then pulls the payment and re-sets the payment_id and payer_id fields from the payment.... then if that was successful, triggers the click.

I'm pretty sure that if we don't get a payment back from PayPal, the button won't click... but at the same time that likely means that the request would fail on the next step anyway, right?

## How has this been tested
**NOT USING THE BUILD PROCESS**, truth be told have no idea how to run it. 

So I've just manually added this into `/src/ee-paypal-smart-buttons.js` after doing all my testing using the version just before this.

Tested by just running through the usual payment process and confirming it still works, I've also commented out the code that sets the values from authData and used just my new code, that worked too.

## Checklist

* [ ] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [ ] User input is adequately validated and sanitized
* [ ] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [ ] My code is tested.
* [ ] My code follows the Event Espresso code style.
* [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by mnelson4** [comment]
Thanks for helping look into the issue @Pebblo. Theoretically this shouldn't be necessary, as we already had the needed info, right? So this is mostly just an extra precaution?

Could you point me to the code examples that use this? If this is what they're all doing then maybe we should too.

Regarding build process, if you're still using that Laragon setup (or have node/npm installed locally), you would open a terminal in the add-on's root folder, and run `npm install` then `npm run watch` and it will take care of taking the source file you have there and writing it to the `assets/dist` folder and then EE will use that generated JS file. Theoretically.

**Comment by mnelson4** [comment]
Hmmm thanks for the reference there @Pebblo.

I skimmed over them, but got a little worried with this change when I spotted a few places where they were actually reporting problems with using `actions.payment.get()`. (https://github.com/paypal/paypal-checkout/issues/769#issuecomment-426602360 and https://github.com/paypal/paypal-checkout/issues/831). 

It seems whatever issue they had was resolved, but it certainly does add another possible point of failure.

So I'm inclined to not make this change until we've confirmed the change I just added (the setTimeout call to delay submitting the form until after the form has been updated) is confirmed to not resolve the issue. If that doesn't do the trick, this is a good plan B (although I'd also like to add some more logging to get more info so we know more about why the error is occurring... right now, it could be because PayPal isn't returning the expected data, or it could be they are and we're sometimes submitting the form before the inputs get updated).

**Comment by mnelson4** [comment]
Oh I forgot too- I think the current implementation already waits for the payment data to arrive before calling the callback of `onAuthorize`. So when that function is called we always have the payment details we need. (We could add some logging to verify that's the case). But theoretically we're already waiting for the data we need, which is one reason I'm inclined to not do it.
Can you somewhat consistently reproduce the issue on an old version of the payment method, and still reproduce it on current master, but not on this branch?

**Comment by Pebblo** [comment]
> I skimmed over them, but got a little worried with this change when I spotted a few places where they were actually reporting problems with using `actions.payment.get()`

Those are basically for the same issue and it took them a while to fix it so there are multiple tickets for it, in short `actions.payment.get()` failed unless `actions.payment.execute()` ran first. You could do it through PHP but not JS.

> So I'm inclined to not make this change until we've confirmed the change I just added (the setTimeout call to delay submitting the form until after the form has been updated) is confirmed to not resolve the issue.

Yeah good call, no objections from me.

> If that doesn't do the trick,

It looks like it did not, Lorenzo updated the ticket a little earlier:

https://github.com/eventespresso/eea-paypal-smart-buttons/issues/24#issuecomment-460666576

> this is a good plan B (although I'd also like to add some more logging to get more info so we know more about why the error is occurring... right now, it could be because PayPal isn't returning the expected data, or it could be they are and we're sometimes submitting the form before the inputs get updated).

Sounds good, but just to clarify, I'm not pushing for this specific fix, this is just what I ended up with when I started digging into it.

> Oh I forgot too- I think the current implementation already waits for the payment data to arrive before calling the callback of `onAuthorize`. So when that function is called we always have the payment details we need. (We could add some logging to verify that's the case). But theoretically we're already waiting for the data we need, which is one reason I'm inclined to not do it.

Yep, I saw that. The biggest difference in this branch is we don't click the 'next' button unless we've pulled a payment object, which should have the needed values.

That reminds me, are we using the additional 2 values at all?

`paymentToken` and `orderID` look like they are for executing the payment after pre-auth, I can't see anywhere we actually use those?

> Can you somewhat consistently reproduce the issue on an old version of the payment method, and still reproduce it on current master, but not on this branch?

This I'll do now and compare.

**Comment by Pebblo** [comment]
@mnelson4 

I had a nice long wall of text to show the testing I'd been doing on this as it took forever to reproduce at first, now I've remove it ( lucky you :) ) as I've found the cause of this and confirmed that it is NOT a timing issue so neither timeout in master, or my fix above fix this at all.

The problem is the elements stroed in:

` this.hidden_input_payer_id
this.hidden_input_payment_id
this.hidden_input_payment_token
this.hidden_input_order_id`

are not always the same elements that are loaded on the page.

Open up a registration, and on the payment options, select PayPal Smart Buttons, the stop.

Now... either click on the PayPal smart buttons payment method icon again, or select another (lets say Stripe) and then go back to PayPal Smart buttons.

Proceed with the payment..... BOOM. The hidden elements for PayPal Smart Buttons do not get set.

(Note I added additional logging to onAuthorize to log the data and [it is all there](https://take.ms/ymwRt), every time, its just that the elements on [SPCO don't get updated.](https://take.ms/P49E3) )

The fix I used to confirm the above was the problem is in `onAuthorize` above everything that's there now, I added:

`this.hidden_input_payer_id = jQuery(this.hidden_input_payer_id_selector);
this.hidden_input_payment_id = jQuery(this.hidden_input_payment_id_selector);
this.hidden_input_payment_token = jQuery(this.hidden_input_payment_token_selector);
this.hidden_input_order_id = jQuery(this.hidden_input_order_id_selector);`

I can now do the above as many times as I want and all works well (tested in 1.0.2.p)

I've not been able to reproduce since adding that above and I know I could set the value using the selects directly rather than assigning them but I'm guessing theres a better fix for this, so didn't commit it.

**Comment by Pebblo** [comment]
Nope, completely agree with not using it.

No need to re-pull details we already have, the only reason for the above was because it appeared we weren't getting those details through at times, so this tried to make sure we at least had the vital one (payerID).

Closing this out as its no longer needed. Thanks Mike.

**Pull request closed without merging**
