### PR TITLE
Fet/better error messages

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

If an admin enters the wrong credentials, gives them a little better of of an error message. Also, gives messages next to the key fields (debug mode, client id and secret).
Addresses https://github.com/eventespresso/eea-paypal-smart-buttons/issues/27

## How has this been tested

* [ ] On this branch, try to save Smart Buttons with bad credentials. You should get a helpful error message saying "PayPal did not accept your API credentials. Double-check your credentials and copy and paste them into the fields again and save changes. Alternatively, create a new app and try the new API credentials." You should also see messages next to the inputs debug mode, client ID, and secret.
* [ ] Verify the payment method still works.

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by mnelson4** [comment]
Passing to Lorenzo for testing and feedback on the strings I ended up using (feel free to tweak them too eh).

**Comment by lorenzocaum** [comment]
Hi Mike, I spotted something on one of the form fields when the validation runs:

image 2018-12-20 at 9 47 11 am

**Comment by mnelson4** [comment]
oh good catch @lorenzocaum, thanks. Passing back to @knazart for review.

**Comment by lorenzocaum** [comment]
Hi Mike, this is ready to be merged in. Thanks!

**Pull request merged**
